### ISSUE TITLE
Fork to background/daemonize (client)

### ISSUE THREAD

**Issue by 0x27** [Numbers11/rvprxmx#2]
It would be interesting to add a --daemon option in the client so that it can fork to background/daemonize (at least on Unix/POSIX systems)

**Comment by Numbers11** [comment]
I don't think we need platform specific code when you can achieve pretty much the same thing with unix on-board commands.

**Comment by 0x27** [comment]
So I've looked into this, seems there is no `fork()` syscall we can use in Golang to do this, so on Unix systems I guess we would just advise doing `nohup` and `disown`. 

For Windows, it seems we would need to run it using `start /B` or similar.

If there is interest, I could look into writing platform specific stuff for Unix/OSX and Windows in a branch, but for now seems you are correct and there is no point :)
